### ISSUE TITLE
Research the history of the Command Line Interface (CLI)

### ISSUE THREAD

**Issue by Sfayson1** [Sfayson1/sfayson-module1#1]
#### Summary
Research the historical development, key milestones, and notable figures in the Command Line Interface (CLI) evolution.

#### Description
- Objective: Gain a comprehensive understanding of the CLI's history to inform future development and educational content.
- Scope: Cover from its inception to current iterations and identify key events, technological advancements, and individuals who have been instrumental in its development.

#### Tasks
1. Trace back to the initial concept of the CLI: Identify the first systems that used command-line interfaces.
2. Identify key milestones:
    - Development of early shells like Bourne Shell, C Shell, etc.
    - Introduction of scripting capabilities
    - Open-source contributions
    - CLI-based utilities and tools (e.g., grep, awk, sed)
3. Note important figures:
    - Who were the pioneers?
    - What organizations were pivotal?
4. Highlight major shifts:
    - Transition from text-based to graphical interfaces and how CLI maintained relevance.
    - Evolution with cloud computing and DevOps culture.
5. Examine current state:
    - Modern CLI tools and frameworks (e.g., PowerShell, Zsh)
    - CLI in cloud computing and microservices
6. Compile information into a coherent report or presentation.

#### Acceptance Criteria
- A detailed report or presentation that covers all the tasks.
- Cite credible sources for all information gathered.
- Provide a timeline that illustrates key events and milestones.
- Identify at least 3-5 notable figures and their contributions.
  
#### Priority
- Medium

**Comment by Sfayson1** [comment]
In the early infancy year of computers, the command line was used as a form of communication through the use of teleprinters. In 1964 Bell Labs joined MIT and GE's computer department (which would later become Honeywell) to create the MULTICS (Multiplexed Information and Computing Service) project. 
In 1964 MIT staffer Louis Pouzin wrote a paper how the MULTICS command language could be designed. He names this idea the shell. In 1965 a software engineer by the name of Glenda Schroeder with the help of an unnamed employee from GE developed the first MULTICS operating system shell.
In 1969 Bell Labs decides to withdraw from the project due to the prolonged costs and no quantifiable end date, although a small group of bell labs employees continued to work on the project on their own.

In 1971 the first UNIX shell called V6 shell was developed by Ken Thompson at Bell Labs. It was modeled after Glenda Schroeder's MULTICS shell. It had limitations because it did not have the ability to script. The bourne shell was introduced in 1977 and created by Stephen R Bourne at Bell Labs for V7 unix. It led to the development of Korn shell, Ash shell, and bash.  Bourne's purpose for the development of the bourne shell was to serve as a command interpreter and to allow for scripting. 

The command line interface (CLI) often left non-technical users feeling overwhelmed. It also lacked the usual feedback which led to user error. The graphical user interface (GUI) emerged as a solution to this problem, to make computers more user friendly to the general public. The first instance of a GUI was introduced in 1984 by Apple. It included icons, to represent files, folders, and applications. This allowed users to interact with the computer with a mouse. This cause Microsoft to the release their version of the GUI soon after Apple. Which began to push the CLI to the background. Cloud platforms like AWS and Azure rely on CLI tools to manage cloud resources, and it allows for automation of those resources. The CLI provides DevOps practices the ability to continuously integrate. While microservices benefit from CLI tools for manage and orchestrating clusters.

**Comment by jeromehardaway** [comment]
@Sfayson1, how do you see the CLI integral to your career goals?

**Comment by jeromehardaway** [comment]
And @Sfayson1, add the explanation you have above to your repo as a PR so I can approve it.

**Comment by Sfayson1** [comment]
The CLI is integral to my career goals because it is the backbone of software development. CLi commands are used when cloning repos, creating branches, committing changes, installing, updating and managing dependencies. Understanding how the CLI works makes me a more efficient engineer.
