### ISSUE TITLE
Navigate to different directories using `cd`

### ISSUE THREAD

**Issue by Sfayson1** [Sfayson1/sfayson-module1#12]
### Ticket: Navigate to Different Directories Using `cd`

---

#### Summary

Create a guide or tutorial demonstrating how to navigate different directories using the `cd` command in the command-line interface.

---

#### Description

- **Objective**: To educate users on effectively using the `cd` command for directory navigation in a Unix-like operating system.
  
- **Scope**: 
  - Basic usage of `cd`
  - Advanced options and flags
  - Common use cases and scenarios
  - Troubleshooting common issues

---

#### Tasks

1. **Basic Usage**: 
  - Explain the simplest form of `cd` and how it works.
  
2. **Advanced Options**: 
  - Cover any flags or options that can be used with `cd.`
  
3. **Common Scenarios**: 
  - Demonstrate how to navigate to parent directories and home directories using relative vs. absolute paths.

4. **Troubleshooting**: 
  - List common issues users might face and how to solve them.

5. **Compile Information**: 
  - Create a guide or tutorial that encapsulates all the above information.

---

#### Acceptance Criteria

- A well-structured guide or tutorial that covers all the listed tasks.
- Include examples and screenshots where applicable.
- Factual accuracy is essential.

---

#### Priority

- Medium

**Comment by Sfayson1** [comment]
![Image](https://github.com/Sfayson1/sfayson-module1/assets/137829671/e4778fa7-f47e-4760-87b5-aa6f017110b8)

**Comment by Sfayson1** [comment]
I wasn't sure how to add this to a pr request.

**Comment by jeromehardaway** [comment]
@Sfayson1 you can put your work in a readMe file in the module repo you have and then PR it there.

**Comment by Sfayson1** [comment]
ok i will do that now then.
